### ISSUE TITLE
opening output file in excel sheet shows error

### ISSUE THREAD

**Issue by SKR301** [SKR301/power-of-2#5]
![image](https://user-images.githubusercontent.com/47807051/196508363-eede5aec-8f4f-4c30-83d2-f7024c4a984e.png)

- create new sheet after each limit?

**Comment by Akshayaap** [comment]
- this is not problem with code. this is problem with libre office, which sucks when there is too much data in spreadsheet.

**Comment by SKR301** [comment]
> * this is not problem with code. this is problem with libre office, which sucks when there is too much data in spreadsheet.

I know. But it needs to be resolved programmatically
